[package]
name = "tools"
version = "0.0.0"

[dependencies]
clap = "2.19.2"
env_logger = "0.4.0"
mdbook = "0.0.21"
pandoc_ast = "0.7.1"
serde_json = "1.0.1"
tempdir = "0.3.5"
tempfile = "2.1.5"
toml = "0.4.5"

[profile.release]
debug = true
